### ISSUE TITLE
Warning message in the PS docker window

### ISSUE THREAD

**Issue by Jeeve65** [Microsoft/nav-docker#176] opened 2018-03-27 10:11 UTC
I installed build 21229. Startup of the docker image goes fine. I installed the certificate and the new AL.vsix.
Deployed our extension from VS code without debugger. The application starts and looks fine, including our extension, but in the powershell window a LONG warning trace shows up, see below.
[Our extension does NOT use calendar entries at all, so I thing it is from the NAV image]

TimeGenerated : 3/27/2018 12:02:23 PM
EntryType     : Warning
Message       : Server instance: NAV
                Tenant ID: default
                <ii>Session type: Background
                Session ID: 32
                User: 
                Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideDuplicate
                KeyException
                Remappable: False
                ErrorCode: 85132273
                ErrorNumber: 1009
                ModuleNumber: 19
                SuppressMessage: False
                ContainsPersonalOrRestrictedInformation: True
                DiagnosticsSuppress: True
                DiagnosticsMessage: The Calendar Event User Config. already 
                exists. Identification fields and values: #! Classified !#
                MessageWithoutPrivateInformation: The Calendar Event User 
                Config. already exists. Identification fields and values: #! 
                Classified !#
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message: <ii>The Calendar Event User Config. already exists. 
                Identification fields and values: User='ADMIN'</ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Runtime.RecordImplementationHelp
                er.MapException(NavCSideException originalException, 
                NCLMetaTable metaTable, IRecordBuffer recordBuffer, Boolean 
                makeNewExceptionRemappable)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.InsertR
                ecordSet(NavDatabase database, NCLMetaTable table, Int32 
                companyIndex, ICollection`1 recordSet, Boolean 
                retrieveTimestamp, NavBigInteger& timestampValue)
                     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.Ins
                ertRecordSet(NCLMetaTable table, List`1 recordSet)
                     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.DoF
                lush(NCLMetaTable table, List`1 bufferedRows, List`1 recordSet)
                     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.Flu
                shBufferedRows(NCLMetaTable table)
                     at Microsoft.Dynamics.Nav.Runtime.SqlTableDataProvider.Try
                GetByPrimaryKey(RecordIdProviderRequest request, 
                ReadOnlyRecordBuffer& recordBuffer)
                     at Microsoft.Dynamics.Nav.Runtime.DataAccess.InternalTryGe
                tByPrimaryKey(RecordIdCacheRequest request, 
                MutableRecordBuffer& recordBuffer)
                     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Fin
                dRecordWithoutCheckingValues(DataError errorLevel, NavValue[] 
                primaryKeyValues, FiltersAndMarks filtersAndMarks, Boolean 
                useRecord, Boolean cacheOnly, Boolean calcAutoCalcFields)
                     at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Get
                Record(DataError errorLevel, NavValue[] values)
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavRecord.ALGet(DataError 
                errorLevel, NavValue[] values)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .GetCalendarEventUserConfiguration_Scope.OnRun()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .GetCalendarEventUserConfiguration(INavRecordHandle 
                calendarEventUserConfig)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .FindOrCreateJobQueue_Scope.OnRun()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .FindOrCreateJobQueue(INavRecordHandle jobQueueEntry)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .CreateOrUpdateJobQueueEntry_Scope.OnRun()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .CreateOrUpdateJobQueueEntry(INavRecordHandle calendarEvent)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .OnInvoke(Int32 memberId, Object[] args)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Record2160.S
                chedule_Scope.OnRun()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Record2160.S
                chedule()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Record2160.O
                nInsert()
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavRecord.Insert(DataError 
                errorLevel, Boolean runApplicationTrigger, Boolean 
                runGlobalTrigger)
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavRecord.ALInsert(DataError 
                errorLevel, Boolean runApplicationTrigger)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .CreateCalendarEventForCodeunit_Scope.OnRun()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .CreateCalendarEventForCodeunit(NavDate scheduledDate, NavText 
                description, Int32 codeunitNo)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit2160
                .OnInvoke(Int32 memberId, Object[] args)
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1352
                .OnRun_Scope.OnRun()
                     at Filter.InvokeWithFilter(NavMethodScope )
                     at Microsoft.Dynamics.Nav.Runtime.NavMethodScope.Run()
                     at Microsoft.Dynamics.Nav.BusinessApplication.Codeunit1352
                .OnRun(INavRecordHandle Îµrec)
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavCodeunit.DoRun(DataError 
                errorLevel, NavRecord record)
                     at Microsoft.Dynamics.Nav.Runtime.NavCodeunit.RunCodeunit(
                DataError errorLevel, Int32 objectId, NavRecord record)
                     at Microsoft.Dynamics.Nav.Runtime.NavTaskScheduler.TaskRun
                nerCodeUnit.RunCodeunit(Int32 codeunitId, NavRecordRef 
                recordRef)
                     at Microsoft.Dynamics.Nav.Runtime.NavTaskScheduler.TaskRun
                nerCodeUnit.TaskSpecificInternalRun()
                Source: Microsoft.Dynamics.Nav.Ncl
                HResult: -2146233088
                ----------------------------------
                Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideDuplicate
                KeyException
                Remappable: True
                ErrorCode: 85132273
                ErrorNumber: 1009
                ModuleNumber: 19
                SuppressMessage: False
                ContainsPersonalOrRestrictedInformation: False
                DiagnosticsSuppress: False
                MessageWithoutPrivateInformation: Error code: 85132273
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message: <ii>Error code: 85132273</ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.CheckAn
                dThrowTrapableErrors(Int32 errorNumber, Exception 
                originalException, NavSqlException 
                transactionNoLongerValidException)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.HandleI
                nnerException(SqlExceptionAdapter exceptionAdapter, String 
                commandText, Boolean isLastExceptionARollbackCause)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.MapExce
                ption(SqlExceptionAdapter exceptionAdapter, String 
                commandText, Boolean isRollbackAction)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass108_0`1.<ExecuteFunction>b__0()
                     at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalActio
                n[T](Func`1 action)
                     at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.SendTr
                aceTagOnThreshold[T](String tag, Category category, Verbosity 
                verbosity, Int32 threshold, Func`1 action, 
                PrivacyClassification classification, String message, Object[] 
                parameters)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.Execute
                FunctionWithTrace[T](EventTask task, Func`1 function, String 
                commandText)
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.ExecuteScalar()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Execute
                AndRetrieveOutputParameters()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Execute
                Insert(IRecordBuffer record, NavAppTableContext tableContext, 
                NavValue resolvedIdentityValue, NavDatabase database, Int32 
                companyIndex, Nullable`1 companyId)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.<>c__Di
                splayClass33_1.<Insert>b__1(NavSqlCommand command)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.Execute
                CommandAndCacheOnSuccess[T](NavSqlCommandCacheKey commandKey, 
                Func`1 newCommandFunc, Func`2 executeFunc)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.Insert(
                NavDatabase database, NCLMetaTable table, Int32 companyIndex, 
                IRecordBuffer record, Boolean retrieveTimestamp, NavValue& 
                identityValue, NavBigInteger& timestampValue)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDmlCommand.InsertR
                ecordSet(NavDatabase database, NCLMetaTable table, Int32 
                companyIndex, ICollection`1 recordSet, Boolean 
                retrieveTimestamp, NavBigInteger& timestampValue)
                Source: Microsoft.Dynamics.Nav.Ncl
                HResult: -2146233088
                ----------------------------------
                Type: System.Data.SqlClient.SqlException
                ClientConnectionId: c0d14d5e-7cef-4819-8f64-4e5d4d1a03b1
                Class: 14
                LineNumber: 1
                Number: 2627
                Server: LOCALHOST\SQLEXPRESS
                State: 1
                Source: .Net SqlClient Data Provider
                ErrorCode: -2146232060
                Message:
                  <ii>Violation of PRIMARY KEY constraint 'CRONUS NL$Calendar 
                Event User Config_$0'. Cannot insert duplicate key in object 
                'dbo.CRONUS NL$Calendar Event User Config_'. The duplicate key 
                value is (ADMIN).
                  The statement has been terminated.</ii>
                StackTrace:
                     at 
                System.Data.SqlClient.SqlConnection.OnError(SqlException 
                exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarnin
                g(TdsParserStateObject stateObj, Boolean 
                callerHasConnectionLock, Boolean asyncClose)
                     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior 
                runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, 
                BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject 
                stateObj, Boolean& dataReady)
                     at 
                System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                     at System.Data.SqlClient.SqlDataReader.get_MetaData()
                     at System.Data.SqlClient.SqlCommand.FinishExecuteReader(Sq
                lDataReader ds, RunBehavior runBehavior, String 
                resetOptionsString, Boolean isInternal, Boolean 
                forDescribeParameterEncryption)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(Co
                mmandBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, Boolean async, Int32 timeout, Task& task, 
                Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean 
                describeParameterEncryptionRequest)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReader(Comma
                ndBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, String method, TaskCompletionSource`1 
                completion, Int32 timeout, Task& task, Boolean& usedCache, 
                Boolean asyncWrite, Boolean inRetry)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReader(Comma
                ndBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, String method)
                     at System.Data.SqlClient.SqlCommand.ExecuteScalar()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass108_0`1.<ExecuteFunction>b__0()
                HResult: -2146232060
                </ii>

**Comment by freddydk** [comment] 2018-03-27 10:16
I don't think this has anything to do with Docker - but I will try to find someone to have a look.
Thanks

**Comment by freddydk** [comment] 2018-03-27 11:20
This has been filed as a bug on the application team.
The reason why you haven't seen this before is, that it is caused by the new docker images having TaskScheduler enabled and this warning is the result of a running background task to update the headlines.

**Comment by freddydk** [comment] 2018-04-01 15:33
I will close the issue here, as it is unrelated to docker.

**Closed by freddydk** 2018-04-01 15:33 UTC
