### ISSUE TITLE
Cannot create an instance of following .net framework object.....

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/nav-docker#192] opened 2018-05-09 09:21 UTC
@freddydk I have my custom dlls, my obects are compiling, but when using them in rtc I m getting error like.

Cannot create an instance of following .net framework object.....

I am running nav 2018 on docker container.

DLLs are configured to run on the server.

I have put my DLLs on this path
C:\ProgramData\NavContainerHelper\Extensions\Development\Program Files\110\RoleTailored Client\Add-ins

I am able to desgin and compile the objects.

**Comment by freddydk** [comment] 2018-05-09 10:07
Duplicate of #190

**Closed by freddydk** 2018-05-09 10:07 UTC
