### ISSUE TITLE
New-NAVContainer Fails with docker Exit Code 125

### ISSUE THREAD

**Issue by GoSolutionsZA** [Microsoft/nav-docker#278] opened 2018-10-12 12:30 UTC
NOTE: Not entirely sure if this is a Docker or NavContainerHelper issue.
When using New-NAVContainer a timeout occurs each time and fails to create the container. I have run out of ideas, hope you can assist?

NOTE: My docker daemon.json has additional "data-root": "E:\\docker" due to small C drive
Might this have something to do with it?

Have tried various commands, all fail in exactly same way, but here is one example:

New-NavContainer -containerName ZZZ-BCW1-DEV -accept_eula -auth Windows -authenticationEMail xxxx.xxxxx@aaaaaaaa.xxxxxx -enableSymbolLoading -imageName microsoft/bcsandbox:w1 -includeCSide -licenseFile 'D:\6133396-V13.flf' -memoryLimit 3G -restart unless-stopped -shortcuts Desktop -updateHosts

**Comment by freddydk** [comment] 2018-10-12 12:37
What version of navcontainerhelper are you using?
You say they fail in the same way, how?

**Comment by GoSolutionsZA** [comment] 2018-10-15 15:41
Thanks Freddy, oddly some of our machines stopped doing this without intervention by Friday 12 Oct, but this one still has the error message in the PS session - attached for interest.

The NavContainerHelper Version is 0.3.1.4 on this failing machine

Thanks, Theo
[Failed New Container.txt](https://github.com/Microsoft/nav-docker/files/2479420/Failed.New.Container.txt)

**Comment by GoSolutionsZA** [comment] 2018-10-15 15:42
Did not really mean to close that..

**Comment by freddydk** [comment] 2018-10-19 05:44
Duplicate of https://github.com/Microsoft/navcontainerhelper/issues/227

**Closed by freddydk** 2018-10-19 05:44 UTC
