### ISSUE TITLE
Unable to start new Container when providing an applicationInsightsKey

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/nav-docker#496] opened 2021-04-20 13:14 UTC
Hi Freddy,

we had some trouble to start up new containers after adding the parameter -applicationInsightsKey.

`The property 'Value' cannot be found on this object. Verify that the property exists and can be set.`

The issue is cause by a typo in SetupConfiguration.ps1.  There you you use the 
` $customConfig.SelectSingleNode("//appSettings/add[@key='applicationInsightsInstrumentationKey']").Value`

it has to be a capital A on Application. 

` $customConfig.SelectSingleNode("//appSettings/add[@key='ApplicationInsightsInstrumentationKey']").Value `

I changed it and used the -myScripts to override it and that seems to fix the issue.
Would be nice to get that one fixed :)

Br. Kristof

**Comment by freddydk** [comment] 2021-04-20 13:29
Will get this fixed and create an updated generic image tomorrow.

**Comment by freddydk** [comment] 2021-04-21 06:11
The problem is only with single tenant containers.

**Comment by freddydk** [comment] 2021-04-21 07:16
fixed in generic image 1.0.1.6

**Closed by freddydk** 2021-04-21 07:16 UTC
