### ISSUE TITLE
ClickOnce deployment failing

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/nav-docker#13] opened 2017-08-11 18:43 UTC
When selecting the parameter -e ClickOnce=Y the script nicely creates a ClickOnce deployment.

**Output:**

```
.
.
Create Web Site
Create NAV Web Server Instance
Create http download site
Create ClickOnce Manifest
Container IP Address: 172.21.64.168
Container Hostname  : 9f88718660a7
Web Client          : https://9f88718660a7/NAV/WebClient/
ClickOnce Manifest  : http://9f88718660a7:8080/NAV

Files:
http://9f88718660a7:8080/certificate.cer
.
.

```
However, when trying to run the deployment, an error appears stating that the deployment could not be started.

**Excerpt from the logfile:**

```
ERROR DETAILS
	Following errors were detected during this operation.
	* [11-8-2017 12:45:40] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
```

**Comment by freddydk** [comment] 2017-08-11 19:33
I will check this

**Comment by Koubek** [comment] 2017-08-11 19:50
@ptijsma - I suppose the error comes from the log of the manifest you run on your host (or pc or whatever). Do you use Google Chrome to open the link? Have you tried to open the page from IE/Edge for example?

**Comment by tfenster** [comment] 2017-08-11 20:27
I can confirm that like for @Koubek it only worked with IE for me, not with Chrome. And it looks like you used nated networking to access the ClickOnce deployment. Did you access it from a second machine using exposed or directly on the Container host? That can lead to a situation where you download the initial file from the container host and then it tries to download the application from the URL/hostname of the Container itself and ClickOnce doesn't like that mismatch. But if I remember correctly that error message is slightly different

**Comment by freddydk** [comment] 2017-08-11 20:29
Maybe I should .zip the clickonce manifest, then you could automate the download and host it on a file share or like, if the container hosted option provides problems?

**Comment by Koubek** [comment] 2017-08-11 20:48
NAT networks are generally problems for many applications served to outside. I have seen many with the problems. 

If anyone insists to run sth. on NAT network and publish it outside, the ideal way to avoid some of the problems is mapping the ports on the same numbers (`host_id : container_port` - both should have the same value). To achieve it (and be able to run more than one container) you need the option to specify the port numbers that will be used internally in the container for each service.

What remains is the hostname inside the package... The manifest points to the container`s hostname so if you want to access using the same package from outside (not from the **docker host**) you are in troubles. This won\`t work right now.

The best way and the most logical one is using **transparent networking** in the cases, you need to publish to the outer world (even on the LAN).

**Comment by tfenster** [comment] 2017-08-11 22:21
I agree with @Koubek, I don't see a good way to get this done with nat networking in a "distributed" scenario where you have a Docker host and other machines as clients. In a "dev" scenario where you e.g. have the Container running on your local laptop and want to connect to it, this should still work fine. Therefore from my point of view we should probably document a bit more about it but we have two valid scenarios (distributed with transparent network and "same machine" with nat) and users just need to understand which one they can use

@ptijsma does it work for you with distibuted / transparent or "same machine / NAT setup in IE?

**Comment by ptijsma** [comment] 2017-08-11 22:44
I'm running it on my local laptop (since my main purpose for Docker containers is to find out if I can easily distribute demo environments of our ISV product amongst our consultants and being able to update them)

I've just tried running the ClickOnce from IE and this indeed did the Trick.
Still strange it doesn't work from Chrome though. In the end it's still just an application manifest being executed.

**Comment by Koubek** [comment] 2017-08-14 17:01
I have explained the problem of the **nat** and the ports (mapping and publishing). And I told that there was also a problem of the **hostname**. You can access using **container name** / **container hostname** from your host. In case you need for any reason access the container behind **nat** from your LAN, you would need to adjust ClickOnce publishing process and inject the hostname you would like to use via an **env variable**. The ClickOnce generator should be able to accept this variable and set **Server** value use this instead of using the container\`s **$hostname**.

But this should be possible, you can try it.

@freddyk - I am not sure if this approach is really necessary to implement in the base image. I still recommend accessing via **transparent** networks in these scenarios. You should decide and eventually close the issue.

@ptijsma - Is this acceptable solution for you (using transparent networks or eventually create your own overrides/solution)?

**Comment by Koubek** [comment] 2017-08-14 17:47
I was thinking about it a little bit more and I think we would need this approach in case we want support Docker Swarm. This approach is actually pretty same we would use for overlay networks and multi-node swarm solution that should be published to the outer world.

I will send you a proposal that would be tested on both, **nat** and **overlay** networks (the second one on the swarm).

**Comment by ptijsma** [comment] 2017-08-14 22:02
Hi @Koubek 

I think the workaround will work, Going forward we should only use Web Client anyway, but for now Windows Client is a must. And since we know it'll be EOL in the (near) future anyways, a workaround will do fine :-)

**Comment by freddydk** [comment] 2017-08-15 17:26
Closing the issue

**Closed by freddydk** 2017-08-15 17:26 UTC

**Comment by iuridavid** [comment] 2018-04-19 08:45
Thank you for the post.
I was struggling with this, but as soon as I tried IE it worked fine.
