### ISSUE TITLE
Running on Azure VM works smoothly

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/nav-docker#20] opened 2017-08-14 16:07 UTC
Got everything up and running on Azure VM.

Comments:
- Download of images is way faster, probably due to hosting of images on Azure Container Registry (I guess).
- Extraction of image files sometimes hangs, but after closing PowerShell and checking the images the downloaded image is available and can be started. This happens with both NAV images and Windows Server Core image.
- VM with SSD drive seems to noticeably faster when it comes to image download / extraction and starting the container
- Starting the container is faster compared to Windows 10 and has less memory consumption
- Publishing ports requires to add an inbound security role on Azure

Now I'm going to test with multiple containers and trying to initialize a classroom setting.

Nice work!

**Comment by Koubek** [comment] 2017-08-14 16:39
Cool!!!

About the performance comparison: 

- On Win2016 you are running by default EE version of Docker which (again, by default) uses **process isolation**  (On Win10 you can use only **hyper-v isolation**, on W2K16 you can choose for each container but there some licensing restrictions when using **hyper-v isolation** on the server). 

- **process isolation** performs much better as this is the native way you can see on Linux. You can see processes using the task manager - in the case of **nav-docker** you will see running SQL and NAV server as well as IIS. And this will be multiplicated by containers you are running on the host.

- **hyper-v isolation** needs to create very lightweight VM to run a container. But still, there is a VM in between. This approach is better in case you need to achieve higher level of the isolation (for any reason you can have) but, and this is obvious, you need to consider performance penalizations.

**Comment by ajkauffmann** [comment] 2017-08-14 17:02
Thanks Koubek. Didn't expect process isolation to be such a big difference. Don't see the separate processes though.

Any idea what memory consumption would be when running up to e.g. 25 nav containers on one single VM?
What about CPU requirements for such set up?
I compared prices for big Azure machines, the larger machines will be cheaper on a daily basis compared to running multiple small VM's.

**Comment by Koubek** [comment] 2017-08-14 17:59
This is what we have on one of the docker servers (there are 2016 and 2017 instances and 2 or 3 CUs running inside):

![image](https://user-images.githubusercontent.com/24265973/29284124-c21958ec-8129-11e7-866e-1540d0764c0a.png)

The problem of the memory actually is that NAV increases the consumption when starting compiling the objects and later based on the demand. So it is pretty unpredictable. Anyway, on W2K16 you don\`t have to set the memory limit to solve the problem we can see on Win10. The memory would be consumed dynamically.

I expect sth. about 850 MB - 1,2 GB per instance but this could vary.

CPU should be optimized better than memory. But again, when compiling the CPU consumption goes pretty high and can use multiple cores.

You can run multiple instances and start using them and then run `docker stats` and watch the results.

One more detail - we in the company use **gMSA** and then I have three SQL instances (different versions) and the NAV containers run only NAV + IIS (with NAV Web). When running without SQL inside the performance is much better in our case. So whenever possible I would recommend using NAV like we do. Of course, I can understand that for classes would be much better to use all-in-one solution. Moreover you do not depend on **gMSA**.

**Comment by tfenster** [comment] 2017-08-14 18:14
I would estimate the NAV memory and CPU consumpition of X container instances almost exactly like the consumption you'd calculate for X NAV instances in one machine because there is a close to 0 overhead for the containers as possible

**Comment by ajkauffmann** [comment] 2017-08-14 20:16
I'm talking about trainings for VS Code, so compiling and deployment is different anyway. Would expect much less impact on the server. Anyway, it seems to be safe to reserve about 2 GB per container. Depending on the number of trainees, we can choose the VM size.

Alternatively, we choose to host the databases on Azure SQL. If we prepare one image with the connection settings, then we only have to change the database name when starting the container. I guess it would save about 500 MB memory per container.

But first step is to find out how we can deploy Extension packages from local VS Code the docker container in Azure VM. Authentication is the challenge here (maybe that's already solved, need to find out). If that works, then it's a matter of preparing images and off we go...

**Comment by tfenster** [comment] 2017-08-14 20:45
You can use UserName authentication. You'd then need to expose 7049 (and 46/47/48, depending on what you need) and 80/443 on the host and map those through Azure admin to make them available externally. If you want everyone to be able to download the .vsix, you'd need to expose 8080 as well. I am wondering if the triple hostname challenge (azure external name vs. azure internal name vs. container internal name) will cause problem. This [https://azure.microsoft.com/en-us/blog/announcing-azure-container-instances/](https://azure.microsoft.com/en-us/blog/announcing-azure-container-instances/) would make it even easier, but I haven't see anything about Windows support there

**Comment by ajkauffmann** [comment] 2017-08-14 21:03
That's what I'm playing with right now. And succeeded to download AL package from Azure VM to local VS Code. 

1. Publish all ports on the container (with -P). No harm is done since those ports are only available inside the Azure VM and not from outside. With -P you get automatic port mapping with random port numbers.
2. Added the generated port numbers for port 8080, 443 and 7049 to Azure security rules.

Now I was able to download vsix, certificate and open the Web Client. With a fully qualified domain name, like `https://mydocker.westeurope.cloudapp.azure.com:10394/NAV/WebClient/`. Login works, so far so good. (BTW, it's FAST !)

Next steps:

3. Install downloaded vsix in Visual Studio 
4. Initialize a new workspace
5. Change these settings in launch.json:

```
"server": "https://mydocker.westeurope.cloudapp.azure.com:10394",
"serverInstance": "NAV",
"port": 36152,
"authentication": "UserPassword",
```

6. Change locale to W1 in app.json
7. Execute command AL:Download symbols

The last step asked for username and password and then nicely downloaded the symbols.

It's very promising...

Next step is to close the loop and publish an extension (expect no problems).

**Comment by ajkauffmann** [comment] 2017-08-14 21:26
Just published the Hello world example to docker container on Azure VM.

The publish process worked without problem. Credentials were taken from the credential cache, didn't have to re-enter them. 

The launch process had some problems. 

- Launch didn't respect the port number in the server setting. See setting in previous post, it has port number 10394. But the composed url in the browser had no port number at all (and used 443 as a result). **That will be a problem with multiple containers running on the same VM**
- The composed url had a debugging context parameter. But then the web client failed with an error message 'Sorry, that didn't work.' The container window showed an event message, which I will post below in a separate message.
- Chrome has a problem with the generated SSL certificate. I have imported the certificate into the trusted root certificates and Edge is happy with that. But Chrome still throws an error: This server could not prove that it is mydocker.westeurope.cloudapp.azure.com; its security certificate does not specify Subject Alternative Names. This may be caused by a misconfiguration or an attacker intercepting your connection.

First two issues should probably also go to the AL project issues. @freddydk, what do you think?

Having said that... Removing the debuggingcontext parameter from the url, adding the correct port number and using Edge, I got the Hello World extension working! Isn't that great?

**Comment by ajkauffmann** [comment] 2017-08-14 21:27
Event viewer message in container related to debuggingcontext parameter:

```
TimeGenerated : 8/14/2017 9:19:05 PM
EntryType     : Warning
Message       : Server instance: NAV
                Category: Runtime
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 408b4b08-f84a-4ccb-aeb3-9ebb416fead7
                ServerActivityId: 8c19bc1f-46b7-45e3-a1aa-83fa8a4eff00
                EventTime: 08/14/2017 21:19:05
                Message <ii>(InvalidOperationException): <ii>Dynamic
                operations can only be performed in homogenous AppDomain.
                ExceptionStackTrace:
                   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T
                ](CallSite`1 site, Object[] args)
                   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TR
                et](CallSite site, T0 arg0, T1 arg1)
                   at Microsoft.Dynamics.Nav.Service.Dev.Web.Controllers.Debugg
                erHub.OnDebuggeeConnected(Object sender,
                DebugSessionStartEventArgs eventArgs)
                   at Microsoft.Dynamics.Nav.Runtime.Debugger.DebugRuntimeManag
                er.OnDebuggingSessionStarted(DebugSessionStartEventArgs e)
                   at Microsoft.Dynamics.Nav.Runtime.NavSession.StartDebuggingS
                ession(String debuggingContext)
                   at Microsoft.Dynamics.Nav.Service.NSService.OpenConnection(C
                onnectionRequest connectionRequest)
                   at SyncInvokeOpenConnection(Object , Object[] , Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                CallerStackTrace:
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pu
                shPopCombinator(ServiceOperation innerOperation, NSServiceBase
                serviceInstance, MethodBase syncMethod, Object[] inputs,
                Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Cr
                eateNewSessionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, Boolean requireNavUser,
                Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Cr
                eateNewAdminSessionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Pe
                rformanceCounterCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tl
                sClearCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass24_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.In
                voke(Object instance, Object[] inputs, Object[]& outputs)
                   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.I
                nvokeBegin(MessageRpc& rpc)
                   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.P
                rocessMessage5(MessageRpc& rpc)
                   at
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean
                isOperationContextSet)
                   at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resume(
                Boolean& alreadyResumedNoLock)
                   at System.ServiceModel.Dispatcher.ThreadBehavior.ResumeProce
                ssing(IResumeMessageRpc resume)
                   at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContext.
                <>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Obje
                ct state)
                   at
                System.Threading.ExecutionContext.RunInternal(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.ExecutionContext.Run(ExecutionContext
                executionContext, ContextCallback callback, Object state,
                Boolean preserveSyncCtx)
                   at System.Threading.QueueUserWorkItemCallback.System.Threadi
                ng.IThreadPoolWorkItem.ExecuteWorkItem()
                   at System.Threading.ThreadPoolWorkQueue.Dispatch()

                </ii></ii>
                ProcessId: 356
                Tag: 00000HC
                ThreadId: 316
                CounterInformation:
```

**Comment by Koubek** [comment] 2017-08-14 21:51
And what about Azure VPN access to avoid the problems? Maybe this isn't an option for you but I can imagine this could solve some of the problems you are facing in your scenario.

**Comment by freddydk** [comment] 2017-08-14 22:00
Debuggingcontext is something I will fix in the image one of the next days.

On the port number, the problem you have (I think) is that the PublicWebBaseUrl in the NAV configuration will need to know what URL points to NAV from the outside and if the port number is wrong, then it won't work. You might need to override some docker installation scripts to manage different foreign ports for the Web Client.

Security Certificate - haven't seen that one before.

**Comment by ajkauffmann** [comment] 2017-08-14 22:01
Not sure what problem would be solved. If I want to to run multiple containers on Azure VM, I need to have multiple port mappings. Only one container can have port 443 mapped. If VS Code uses the port number that was specified in the server URL then there was one problem down.

The other one is the debugger context. That's a .Net problem and I guess it's due to the fact that NAV is running in an isolated process. So it would be nice to have a setting in VS Code to not debug (maybe there is already, or maybe I shouldn't use F5 to test the extension).

Correct me if I'm wrong. I'm on a steep learning curve these days...

**Comment by freddydk** [comment] 2017-08-14 22:05
What you are looking for here is really to be able to specify the ports like

-e webClientPort=61002

etc. for all 5 ports.

Might be a good idea.


/Freddy

**Comment by ajkauffmann** [comment] 2017-08-14 22:11
Interesting idea about port numbers, @freddydk.

Simple test with the docker container stopped proves that VS Code sends a request to the correct port number (from VS Code console). Obviously there is a redirect to the same url without port number. Could it have something to do with tenant redirection? (alternate tenant isn't used, but I don't know if the rewrite url config in IIS is enabled inside the container).

If port numbers need to be changed in the container, then we definitely need to know the mapping during start of the container. Would that be possible with a generated mapping (using the -P parameter)? If not, then we can only use predefined port mappings.

Regarding debugging: Ctrl+F5 is the solution, that is publish without debugging.

**Comment by Koubek** [comment] 2017-08-14 22:13
About the ports you are completely right, sorry for that. As you are running on W2k16 you cannot access natted resources from the host itself using the container names. This is actually possible on win10 where you can run (for example) 20 containers and access each of them using it's name like you are accessing separate VMs on the LAN: https://cont-01or https://cont-02 etc
 But only from the host. So the VPN here could work (or I expect it could).

**Comment by freddydk** [comment] 2017-08-14 22:15
You cannot rely on the auto-mapping of random ports with -p – you would have to do that yourself in powershell when creating the container. NAV needs to know the public URLs.

For debugging – the missing config setting is

<NetFx40_LegacySecurityPolicy enabled="false"/>

In the server.exe.config file.

/Freddy

**Comment by tfenster** [comment] 2017-08-14 22:27
I fully agree, an optional setting allow port definitions would be good. You could then expose them to the same ports on the azure host and map them to external azure ports. No confusion because of different port numbers internally and externally

**Comment by tfenster** [comment] 2017-08-14 22:35
The challenge will probably be how to expose those ports. You would only know during runtime which ports to expose, but the exposed ports have to be defined in the Dockerfile before docker build

**Comment by freddydk** [comment] 2017-08-14 22:58
On DebuggingContext - if you cannot wait - override SetupConfiguration.ps1 with this code:
$serviceTierFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service").FullName
$serverConfigFile = Join-Path $ServiceTierFolder "Microsoft.Dynamics.Nav.Server.exe.config"
$serverConfig = [xml](Get-Content -Path $serverConfigFile)
$serverConfig.SelectSingleNode("//configuration/runtime/NetFx40_LegacySecurityPolicy").enabled = "false"
$serverConfig.Save($serverConfigFile)
and call the default SetupConfiguration.ps1 - then debugging in VS Code should work:-)
New images will be created one of the next days.

**Comment by ajkauffmann** [comment] 2017-08-15 07:47
I can wait... have other stuff to do like work for customers...

Regarding exposing ports, I think the only option to run multiple docker containers is to use reverse proxy. Here is a good read how that could work, using Traefik proxy: https://stefanscherer.github.io/how-to-run-encrypted-windows-websites-with-docker-and-traefik/. With Docker Compose it should be easy to get a complete environment up and running.

Alternatively nginx could also do the trick. Seems that Traefik is the better suited and simpler to use.

Anyway, with a reverse proxy we would be able to run multiple containers on a VM and access them from outside based on the hostname, like container01.navdemo.net, container02.navdemo.net, etc. For a workshop setup this is an absolute must have.

**Comment by Koubek** [comment] 2017-08-15 07:53
Yes, **traefic** should solve the problem in a generic way. This would be probably the best way and it is true that in Docker worlds is being used very frequently.

**Comment by freddydk** [comment] 2017-08-15 07:58
Correct and as Tobias mentions, EXPOSE is a static thing, so the ports inside the container will always be the same. It is however a normal scenario (for purposes other than having multiple containers in one host) to change some ports, so for that I will add some parameters to specify to the NAV container which ports are used publicly to access WebClient, WinClient, Soap and OData. These are then used in the config file and the GETURL AL function will subsequently return correct values when you try to get the url for a page or like.
You still have the option to use traefik or other things.

**Comment by Koubek** [comment] 2017-08-15 08:03
I have been testing something similar (to be able to specify the ports) using the following in `SetupVariables.ps1`:

```PowerShell
$portNavMgtSvc = if ([System.String]::IsNullOrEmpty($env:portNavMgtSvc)) { 7045 } else { $env:portNavMgtSvc }
$portNavSvc = if ([System.String]::IsNullOrEmpty($env:portNavSvc)) { 7046 } else { $env:portNavSvc }
$portNavSoapSvc = if ([System.String]::IsNullOrEmpty($env:portNavSoapSvc)) { 7047 } else { $env:portNavSoapSvc } 
$portNavODataSvc = if ([System.String]::IsNullOrEmpty($env:portNavODataSvc)) { 7048 } else { $env:portNavODataSvc } 
$portNavDevSvc = if ([System.String]::IsNullOrEmpty($env:portNavDevSvc)) { 7049 } else { $env:portNavDevSvc }
```

And then using the variables in the scripts instead of the fixed values.

**Comment by freddydk** [comment] 2017-08-15 08:07
the 7045 and 7049 ports shouldn't change (or rather - they are not referenced anywhere in a config file to be used from the outside). And the Web Client port should also be added (the default for that is depending on whether or not you use SSL though).
I will be checking in a fix today.

**Comment by ajkauffmann** [comment] 2017-08-15 08:12
launch.json has a port setting which overrides the default port 7049. I was able to download symbols and publish an extension using a random port number, assigned by docker.

**Comment by Koubek** [comment] 2017-08-15 08:13
OK, I was thinking of a fully flexible solution so I have started changing all NAV ports. Web Client port should be added, of course, I haven\`t included it yet.

**Comment by freddydk** [comment] 2017-08-15 08:18
Koubek - but you cannot EXPOSE them after build right?

AJ - korrekt 7049 is easy - you can connect to that on any port when mapped. The problem is that NAV needs to know the URL in the config file for connecting to NAV from the outside - NAV needs to know the ports for WinClient, OData, Soap and WebClient - else we will run into errors.

**Comment by Koubek** [comment] 2017-08-15 08:19
You can expose then with `docker run --expose=[]`

**Comment by freddydk** [comment] 2017-08-15 08:23
so
docker run -p 61000:7048 -e PublicODataClientPort 61000  ...
vs
docker run --expose [61000] -e Odataportsvc=61000 ...

I prefer no. 1 - so that inside the container ports are static and you can map them if you want - just remember to tell NAV what you map them to.

**Comment by ajkauffmann** [comment] 2017-08-15 08:32
Option 1 would do the trick. Don't see a reason to change default port numbers inside the container.
Combined with the public hostname, it can create the correct base url's in the settings file (I assume that was what you were talking about).

Number of env variables are increasing rapidly. I recommend to start using the --env-file parameter. ;-)

**Comment by tfenster** [comment] 2017-08-15 08:35
I personally would prefer something like "Offset" or "Startport" so that we could e.g. do the following:
```
docker run -p 61000-61004:7045-7049 -e Startport=61000
```

**Comment by freddydk** [comment] 2017-08-15 08:37
and what about the Web Client?

**Comment by tfenster** [comment] 2017-08-15 08:39
61080 / 61443 maybe? So the full command would then be
```
docker run -p 61000-61004:7045-7049 -p 61080:80 -p 61443:443 -e Startport=61000
```

**Comment by freddydk** [comment] 2017-08-15 08:43
That becomes to much "magic" and something that is hard to understand if you didn't read this thread.
I will add the 4 optional parameters
publicWebClientPort
publicODataPort
publicWinClientPort
publicSoapPort
and if you don't specify them, then default values will be used.

**Comment by tfenster** [comment] 2017-08-15 08:47
wouldn't you need different ports for Web Client with and without SSL? And why didn't you include the DevServicePort and the MgmtServicePort?

**Comment by freddydk** [comment] 2017-08-15 08:53
No, the Web Client has one port.
Remember - the ONLY reason, that the NAV Container needs this info is, to write it in the customsettings.config in the settings:
PublicWebBaseUrl
PublicODataBaseUrl
PublicSoapBaseUrl
PublicWinBaseUrl
If it wasn't for these settings, the NAV server wouldn't care whether or not you mapped the ports.
Since Management and developer ports are not there - no need to specify values to the server it doesn't need

**Comment by tfenster** [comment] 2017-08-15 08:54
ok, understood. Thanks

**Comment by freddydk** [comment] 2017-08-15 17:24
Fixes checked in, generic image built and pushed.
Devpreview images for August and July being built and pushed now.
2017 and 2016 CU's will be built overnight.

**Closed by freddydk** 2017-08-15 17:24 UTC
