### ISSUE TITLE
Virus warning in BC sandbox 15.2.39558.0-se

### ISSUE THREAD

**Issue by mhoury** [microsoft/nav-docker#440] opened 2020-01-10 10:01 UTC
Hi,
Not sure who can help with this.

when trying to pull the latest the BC sandbox image 15.2.39558.0-se we receive a virus/threat warning from VSCode and Windows defender.

threat name: HackTool:JS/Revobfoos.D
located in file:

> file: _F:\ProgramData\Docker\tmp\hcs623963371\Files\Windows\WinSxS\amd64_microsoft-windows-ra-mgmt-wmiv2provider_31bf3856ad364e35_10.0.14393.0_none_6dd47e8d14da7755\PS_RemoteAccessRoutingDomain_v1.0.cdxml_

Is this something that can be ignored or is there something wrong with the image?

**Comment by freddydk** [comment] 2020-01-10 10:59
What is the full image name you are pulling?
mcr.microsoft.com/businesscentral/sandbox:15.2.39558.0-se-ltsc2019 ?

**Comment by freddydk** [comment] 2020-01-10 10:59
and when do you get the warning? when you pull or when you run?

**Comment by mhoury** [comment] 2020-01-10 11:11
full image name is mcr.microsoft.com/businesscentral/sandbox:15.2.39558.0-se

it is hard to pin point the exact section causing this issue, but usually it is when extracting 55d044e60c89 during pulling

**Comment by freddydk** [comment] 2020-01-10 11:13
which windows version is your host computer?

**Comment by mhoury** [comment] 2020-01-10 11:15
Windows 10 v1903

**Comment by freddydk** [comment] 2020-01-10 11:16
and what command are you using?

**Comment by mhoury** [comment] 2020-01-10 11:17
I started with new-bccontainer, when i got the error i tried again with just docker pull but i got the same result

**Comment by mhoury** [comment] 2020-01-10 11:18
this is the full text of the error:

> DockerDo : failed to register layer: re-exec error: exit status 1: output: time="2020-01-10T10:30:39+01:00" level=error msg="hcsshim::ImportLayer - failed failed in Win32: Operati 
> on did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)" error="hcsshim::ImportLayer - failed failed in Win32: Operation did no 
> t complete successfully because the file contains a virus or potentially unwanted software. (0xe1)" importFolderPath="F:\\ProgramData\\Docker\\tmp\\hcs623963371" path="\\\\?\\F:\\ 
> ProgramData\\Docker\\windowsfilter\\f9276919954d09e5811098545d6061c0af7763fb5b5f3cfe1271619c36262c71"
> hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)
> ExitCode: 1
> Commandline: docker pull  mcr.microsoft.com/businesscentral/sandbox:15.2.39558.0-se
> At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.17\ContainerHandling\New-NavContainer.ps1:444 char:13
> +             DockerDo -command pull -imageName $imageName | Out-Null
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment] 2020-01-10 11:19
what command are you using?
new-navcontainer....????

**Comment by mhoury** [comment] 2020-01-10 11:19
here is the error i get when using only docker pull

> failed to register layer: re-exec error: exit status 1: output: time="2020-01-10T11:14:26+01:00" level=error msg="hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)" error="hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)" importFolderPath="F:\\ProgramData\\Docker\\tmp\\hcs236156959" path="\\\\?\\F:\\ProgramData\\Docker\\windowsfilter\\b900314e9c46a939aed10b44fcf0440995efaffe29e1b9f9669b55f99d58f4d0"
> hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)

**Comment by mhoury** [comment] 2020-01-10 11:20
> what command are you using?
> new-navcontainer....????

used the New-BCContainer to get the first error then docker pull and got the second error.

**Comment by freddydk** [comment] 2020-01-10 11:28
Everything on mcr gets scanned after it is build by our build servers, pretty sure everything is clean.

If I could get the full new-bccontainer (which is just an alias for new-navcontainer) - then I can see why you are pulling windows server 2016 image on a windows 10 1903.

Also what antivirus are you running?

**Comment by Koubek** [comment] 2020-01-10 11:39
I think I saw the same on the new WinServer 2019 server when I was pulling the latest (but LTSC 2016) image. Then I was pulling LTSC 2019 version of the same image and it was OK. I just saw the result but haven't been investigating more as I haven't free time. I still have the session open to check it later (maybe tonight or during the weekend).

**Comment by freddydk** [comment] 2020-01-10 12:01
I have tried to pull both the 2016 and 2019 images with the same name without any issue.

**Comment by mhoury** [comment] 2020-01-10 12:23
> Everything on mcr gets scanned after it is build by our build servers, pretty sure everything is clean.
> 
> If I could get the full new-bccontainer (which is just an alias for new-navcontainer) - then I can see why you are pulling windows server 2016 image on a windows 10 1903.
> 
> Also what antivirus are you running?

antivirus is Microsoft's own windows security.

@freddydk , you mentioned that the windows 2016 image is being downloaded, is that something I can declare explicitly in the command so I always get the windows 10 version?

**Comment by Koubek** [comment] 2020-01-10 14:38
I can confirm (Windows Server 2019 OS) the following:

### Defender without exclusion on the Docker appdata folder resulted in:
   * **microsoft/dynamics-nav** or **mcr.microsoft.com/businesscentral/onprem**
```PowerShell
failed to register layer: re-exec error: exit status 1: output: time="2020-01-10T13:17:58Z" level=error msg="hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)" error="hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)" importFolderPath="E:\\ProgramData\\Docker3\\tmp\\hcs633993491" path="\\\\?\\e:\\ProgramData\\Docker3\\windowsfilter\\2f3b088f9b352e4d30c5cfb7d61e40741d8ec1949924ffd8ccabbdf8a776e184"
hcsshim::ImportLayer - failed failed in Win32: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (0xe1)
```

   * **microsoft/dynamics-nav:ltsc2019** or **mcr.microsoft.com/businesscentral/onprem:ltsc2019** are **OK**

### Defender with the exclusion of the docker app folder:
   * **microsoft/dynamics-nav** or **mcr.microsoft.com/businesscentral/onprem** are **OK**
   * **microsoft/dynamics-nav:ltsc2019** or **mcr.microsoft.com/businesscentral/onprem:ltsc2019** are **OK**

**Comment by freddydk** [comment] 2020-01-10 15:30
Thanks @Koubek - that means that whatever the virus scanner identifies as a virus has been there for many many months and the check is new.
Also the thread is inside the server core image - you should get the same problem with WindowsServerCore alone?

**Comment by andrewhickman** [comment] 2020-01-10 15:39
I get the same issue on `mcr.microsoft.com/powershell:windowsservercore-1809`

**Comment by mhoury** [comment] 2020-01-10 16:58
Thanks @Koubek ,
I actually just disabled the anti-virus program to install the image... But as soon as I restore the AV program, the files causing the problems are quarantined.

**Comment by yrest** [comment] 2020-01-10 17:32
Same here on bcinsider.azurecr.io/bcsandbox-master:gb
![image](https://user-images.githubusercontent.com/18675847/72173208-ef57a700-33ce-11ea-833c-92e98c3e6070.png)

News column: Microsoft started distributing viruses! ;)

**Comment by freddydk** [comment] 2020-01-10 19:27
@yrest - as you can see above, the situation appears on images that are 6+ months old and also servercode base images. My assumption is that this is a false positive and the problem really is that defender started looking for something new, in a wrong way.
My assumption is that a lot of people in Microsoft is looking at this issue and I will rest my case.

**Comment by freddydk** [comment] 2020-01-10 20:54
Heard back from the defender team - the issue should be fixed with defender update 1.307.2113.0  or later (not released yet, but will be as soon as they can)

**Comment by yrest** [comment] 2020-01-10 22:52
Brilliant, thanks Freddy!

**Comment by yrest** [comment] 2020-01-11 19:58
seems fine now, I believe the issue is resolved.

**Closed** 2020-01-13 00:02 UTC
Labels: Unrelated to NAV/BC on Docker
