### ISSUE TITLE
Unable to browse to docker container by its hostname

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/nav-docker#19] opened 2017-08-14 07:11 UTC
When the container is started it tells you the web client url, e.g. http://759e5fac726d:8080/NAV/WebClient/

However, the browser isn't able to resolve the hostname to the ip address of the container.
Replacing the hostname with the ip-address works, so that proves that the network connection is ok.

**Comment by tfenster** [comment] 2017-08-14 07:14
Did you specify any network param and if yes, which one? And did you map any ports through -p params?

**Comment by freddydk** [comment] 2017-08-14 07:16
WebClient is not on port 8080 - 8080 is the file share.
I assume you have a typo above.
Can you ping the hostname?

**Comment by ajkauffmann** [comment] 2017-08-14 07:19
yes, that is a typo, copied the wrong url and corrected it, but overlooked port number.

Did not map any port, everything is on the same box (my local Windows 10 machine).
No network params whatsoever, just started the container with the minimum parameters:

docker run -m 4G -e ACCEPT_EULA=Y 33

(33 refers to the image id)

ping to the hostname doesn't work either

**Comment by freddydk** [comment] 2017-08-14 07:20
Does the ping hostname resolve the hostname to IP?

**Comment by ajkauffmann** [comment] 2017-08-14 07:21
no, ping does not resolve the hostname

**Comment by tfenster** [comment] 2017-08-14 07:21
kind of reaching, but could you try ipconfig /flushdns?

**Comment by ajkauffmann** [comment] 2017-08-14 07:22
PS C:\Users\ajkauffmann> ping 3fd1a587638d
Ping request could not find host 3fd1a587638d. Please check the name and try again.
PS C:\Users\ajkauffmann> ping 172.20.231.249

Pinging 172.20.231.249 with 32 bytes of data:
Reply from 172.20.231.249: bytes=32 time=1ms TTL=128
Reply from 172.20.231.249: bytes=32 time<1ms TTL=128
Reply from 172.20.231.249: bytes=32 time<1ms TTL=128
Reply from 172.20.231.249: bytes=32 time<1ms TTL=128

Ping statistics for 172.20.231.249:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms
PS C:\Users\ajkauffmann> ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.
PS C:\Users\ajkauffmann> ping 3fd1a587638d
Ping request could not find host 3fd1a587638d. Please check the name and try again.
PS C:\Users\ajkauffmann>

**Comment by freddydk** [comment] 2017-08-14 07:26
what does docker inspect 3fd1a587638d say?

**Comment by ajkauffmann** [comment] 2017-08-14 07:27
PS C:\Users\ajkauffmann> docker inspect 3fd1a587638d
[
    {
        "Id": "3fd1a587638d38152cd641f4b364f559ed4c3e35d934d826117a6a50030be22a",
        "Created": "2017-08-14T07:18:19.0762741Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1484,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-08-14T07:18:36.0411547Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2017-08-14T09:23:47.7415764+02:00",
                        "End": "2017-08-14T09:23:52.6882904+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-08-14T09:24:22.6887113+02:00",
                        "End": "2017-08-14T09:24:27.4929323+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-08-14T09:24:57.493429+02:00",
                        "End": "2017-08-14T09:25:00.9029313+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-08-14T09:25:30.9030877+02:00",
                        "End": "2017-08-14T09:25:34.5289821+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-08-14T09:26:04.53044+02:00",
                        "End": "2017-08-14T09:26:08.0039507+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:332a8ec3d93394a81ec9a41efc3f7cf935005f9bf3629e4102a7e5b1645d1508",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\3fd1a587638d38152cd641f4b364f559ed4c3e35d934d826117a6a50030be22
a\\3fd1a587638d38152cd641f4b364f559ed4c3e35d934d826117a6a50030be22a-json.log",
        "Name": "/jovial_pasteur",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                50,
                120
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\3fd1a587638d38152cd641f4b364f559ed4c3e35d934d826117a6a50
030be22a"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "3fd1a587638d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ACCEPT_EULA=Y",
                "exe=https://go.microsoft.com/fwlink/?linkid=840945",
                "box=https://go.microsoft.com/fwlink/?linkid=840944",
                "sa_password=_",
                "attach_dbs=[]",
                "DatabaseServer=localhost",
                "DatabaseName=CRONUS"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "33",
            "Volumes": null,
            "WorkingDir": "C:\\",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "w1",
                "created": "201708111854",
                "cu": "august",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "version": "10.0.18032.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "5a28a0b6cbd2900a834972e38e2634830df5e981ea534c0e007d7727fa926cf9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "5a28a0b6cbd2",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "5212a58498a98348d43cce56a26fc400088b738038eb8d03e70808d62fc16c4b",
                    "EndpointID": "b8076967782b7aed28a64d6bd0df521fa8bb03de2998f845429d465ef21e8ff6",
                    "Gateway": "172.20.224.1",
                    "IPAddress": "172.20.231.249",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:66:2c:97",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by tfenster** [comment] 2017-08-14 07:32
What does 
```
get-itemproperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters'
```
return inside the container?

**Comment by freddydk** [comment] 2017-08-14 07:35
That one should be set in the generic dockerfile:
Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord; \

**Comment by freddydk** [comment] 2017-08-14 07:35
Did you try to restart the host

**Comment by ajkauffmann** [comment] 2017-08-14 07:36
PS C:\Users\ajkauffmann> docker exec 3f powershell 'get-itemproperty -path ''HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters'''


ServerPriorityTimeLimit : 0
ServiceDll              : C:\Windows\System32\dnsrslvr.dll
ServiceDllUnloadOnStop  : 1
PSPath                  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHIN
                          E\SYSTEM\CurrentControlSet\Services\Dnscache\Paramete
                          rs
PSParentPath            : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHIN
                          E\SYSTEM\CurrentControlSet\Services\Dnscache
PSChildName             : Parameters
PSDrive                 : HKLM
PSProvider              : Microsoft.PowerShell.Core\Registry

**Comment by tfenster** [comment] 2017-08-14 07:37
Yes, just wondering if somehow this didn't work. But as the output shows, it did...

**Comment by ajkauffmann** [comment] 2017-08-14 07:37
did already a restart of the host

**Comment by freddydk** [comment] 2017-08-14 07:38
I assume that you will have this problem with any docker image you try to run - could you try that?
Remove the images, run the IIS image or like - and test?

**Comment by ajkauffmann** [comment] 2017-08-14 07:40
I had this with both nav2017 image and devpreview image.
Will download a default image (e.g. hello world, server core, whatever) and test, give me a few minutes to download that thing

**Comment by Koubek** [comment] 2017-08-14 07:41
Do you run default Docker configuration? I mean no **config** tweaks, no docker swarm?

Can you run `docker network inspect nat`?

**Comment by ajkauffmann** [comment] 2017-08-14 07:43
not a single tweak so far, no swarm (yet)

PS C:\Users\ajkauffmann> docker network inspect nat
[
    {
        "Name": "nat",
        "Id": "5212a58498a98348d43cce56a26fc400088b738038eb8d03e70808d62fc16c4b",
        "Created": "2017-08-12T23:44:43.6465817+02:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.20.224.0/20",
                    "Gateway": "172.20.224.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "3fd1a587638d38152cd641f4b364f559ed4c3e35d934d826117a6a50030be22a": {
                "Name": "jovial_pasteur",
                "EndpointID": "b8076967782b7aed28a64d6bd0df521fa8bb03de2998f845429d465ef21e8ff6",
                "MacAddress": "00:15:5d:66:2c:97",
                "IPv4Address": "172.20.231.249/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "f794326a-64d1-428f-9319-7bf928cb6be3",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]

**Comment by Koubek** [comment] 2017-08-14 07:44
You can also try to inject the hostname using `--hostname mycontainer` and try to access via `mycontainer`.

To test it just run `docker run -it --rm --hostname mycontainer microsoft/windowsservercore powershell` and then from another cmd try to ping it.

**Comment by ajkauffmann** [comment] 2017-08-14 07:57
same behavior with image windowsservercore

PS C:\Users\ajkauffmann> docker ps
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS              PORTS
0c9996edd01e        microsoft/windowsservercore   "powershell"        43 seconds ago      Up 21 seconds
PS C:\Users\ajkauffmann> ping mycontainer
Ping request could not find host mycontainer. Please check the name and try again.
PS C:\Users\ajkauffmann> ping 172.20.227.14

Pinging 172.20.227.14 with 32 bytes of data:
Reply from 172.20.227.14: bytes=32 time=1ms TTL=128
Reply from 172.20.227.14: bytes=32 time=1ms TTL=128
Reply from 172.20.227.14: bytes=32 time=1ms TTL=128
Reply from 172.20.227.14: bytes=32 time=1ms TTL=128

Ping statistics for 172.20.227.14:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 1ms, Average = 1ms
PS C:\Users\ajkauffmann>

from docker container inspect 0c (to prove actual container hostname is mycontainer):

"Config": {
    "Hostname": "mycontainer",
    "Domainname": "",
    "User": "",
    "AttachStdin": true,
    "AttachStdout": true,
    "AttachStderr": true,
    "Tty": true,
    "OpenStdin": true,
    "StdinOnce": true,
    "Env": null,
    "Cmd": [
        "powershell"
    ],
    "Image": "microsoft/windowsservercore",
    "Volumes": null,
    "WorkingDir": "",
    "Entrypoint": null,
    "OnBuild": null,
    "Labels": {}
},
"NetworkSettings": {
    "Bridge": "",
    "SandboxID": "408e6002908be52b991785881cb1fef25a8d42dba88fffbae451492f75402f67",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": {},
    "SandboxKey": "408e6002908b",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "MacAddress": "",
    "Networks": {
        "nat": {
            "IPAMConfig": null,
            "Links": null,
            "Aliases": null,
            "NetworkID": "5212a58498a98348d43cce56a26fc400088b738038eb8d03e70808d62fc16c4b",
            "EndpointID": "123a80548110656a55c10004d86a1ebe9c70403ad6df26aae97ee515eda41fc9",
            "Gateway": "172.20.224.1",
            "IPAddress": "172.20.227.14",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": "00:15:5d:66:2f:a4",
            "DriverOpts": null
        }
    }
}

**Comment by freddydk** [comment] 2017-08-14 07:58
So we know now that the problem is unrelated to the NAV image. Maybe uninstall and reinstall Docker?

**Comment by Koubek** [comment] 2017-08-14 08:04
Yes, the problem could be related somehow to your current configuration of the host (Win10). Could you run the following: `netsh interface ipv4 show interfaces` or/and alternatively `netsh interface ipv6 show interfaces` and provide the results? Also, the following could be useful: `Get-NetAdapter`.

As @freddydk says, maybe reinstall the docker could solve the problems. BTW, there are experimental features in the docker config enabled by default (or at least in my version this flag was active by default). Maybe you could disable them and test again.

**Comment by Koubek** [comment] 2017-08-14 08:05
![image](https://user-images.githubusercontent.com/24265973/29263188-14f9ab90-80d8-11e7-9cde-2dd480141844.png)

**Comment by ajkauffmann** [comment] 2017-08-14 08:10
Reinstalled docker. Same behavior.

```
PS C:\Users\ajkauffmann> netsh interface ipv4 show interfaces

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  6          65        1500  disconnected  Bluetooth Network Connection
 16          25        1500  disconnected  Local Area Connection* 2
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 21          15        1500  disconnected  vEthernet (External Network (WiFi))
  5          25        1500  connected     vEthernet (External Network (LAN))
 33          15        1500  connected     vEthernet (DockerNAT)
 23          15        1500  connected     vEthernet (HNS Internal NIC)

PS C:\Users\ajkauffmann> netsh interface ipv6 show interfaces

Idx     Met         MTU          State                Name
---  ----------  ----------  ------------  ---------------------------
  6          65        1500  disconnected  Bluetooth Network Connection
 16          25        1500  disconnected  Local Area Connection* 2
  1          75  4294967295  connected     Loopback Pseudo-Interface 1
 21          15        1500  disconnected  vEthernet (External Network (WiFi))
  5          25        1500  connected     vEthernet (External Network (LAN))
 33          15        1500  connected     vEthernet (DockerNAT)
 23          15        1500  connected     vEthernet (HNS Internal NIC)

PS C:\Users\ajkauffmann> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
vEthernet (DockerNAT)     Hyper-V Virtual Ethernet Adapter #3          33 Up           00-15-5D-01-6F-35        10 Gbps
Ethernet                  Microsoft Network Adapter Multiplexo...      27 Disconnected E4-A4-71-12-B1-4B          0 bps
vEthernet (HNS Interna... Hyper-V Virtual Ethernet Adapter #6          23 Up           00-15-5D-66-2D-4A        10 Gbps
vEthernet (Internal Et... Hyper-V Virtual Ethernet Adapter #4           3 Not Present  00-15-5D-01-6F-22          0 bps
vEthernet (External Ne... Hyper-V Virtual Ethernet Adapter #2           5 Up           84-7B-EB-51-88-B2         1 Gbps
vEthernet (External Ne... Hyper-V Virtual Ethernet Adapter             21 Disconnected E4-A4-71-12-B1-4B        10 Gbps
Bluetooth Network Conn... Bluetooth Device (Personal Area Netw...       6 Disconnected E4-A4-71-12-B1-4F         3 Mbps
Ethernet 2                Realtek USB GbE Family Controller            18 Up           84-7B-EB-51-88-B2         1 Gbps
Wi-Fi                     Intel(R) Dual Band Wireless-AC 8260           4 Disconnected E4-A4-71-12-B1-4B          0 bps
```

**Comment by Koubek** [comment] 2017-08-14 08:11
I suppose the problem could be also hyper-v related. Maybe some configs etc. I hadn\`t been using hyper-v on my local machine before I started with containers so I am using everything pretty standard. But I can imagine if somebody using frequently with multiple network interfaces...

**Comment by ajkauffmann** [comment] 2017-08-14 08:20
That rings a bell, Jakub...

I'm using Hyper-V extensively. When I start a VM it often connects to the wrong network adapter. E.g. wifi while I´m on Ethernet. It could happen that the VM started by docker is having the same problem: it connects to the wrong network adapter.

Switching to the correct network adapter is pretty easy in Hyper-V. But... not with the docker VM because that one doesn't come up in the Hyper-V console. Need to figure out if I can change default adapter or use PowerShell to change it after the VM has been started by docker.

**Comment by Koubek** [comment] 2017-08-14 10:47
@ajkauffmann - My this is a silly question but wouldn\`t be possible to create a bridge for both adapters use usually mix (wifi + ethernet). I am not sure if this would work with docker nat.

**Comment by Koubek** [comment] 2017-08-14 10:58
This is what I am using currently on my local Win10 machine. The bridge. I can switch between Ethernet and Wifi. I also use VPN (almost always) and when going from my house (I have VPN tunnel on my Mikrotik router) and need to switch to another network I also need to use my "road warrior" VPN access. And I don\`t have any problems (with docker and with networking generally).

Of course, I still don\`t use hyper-v excessively (sometimes I create a VM to test something but not very frequently).

![image](https://user-images.githubusercontent.com/24265973/29268972-7d60c68e-80ef-11e7-95ea-c605d8895f82.png)

**Comment by ajkauffmann** [comment] 2017-08-14 12:04
Tried to play around with network settings, vSwitches and bridges. All to no avail.
Must be something with the Hyper-V settings. And I'm afraid to screw up my Azure VM's, so I leave it here.
Will switch to docker on Windows Server, either local VM or on Azure. Probably Azure, because I want to find out if I can use this to set up a classroom environment with multiple installations.

**Comment by ajkauffmann** [comment] 2017-08-14 12:04
Thanks for all the help and suggestions so far!

**Comment by freddydk** [comment] 2017-08-14 12:06
On Azure - Windows Server 2016 with Containers is exactly what the title says
Windows Server 2016 with Docker pre-installed.
Works great for the purpose.
I will close this issue now.

**Closed by freddydk** 2017-08-14 12:06 UTC
