### ISSUE TITLE
Adding -ManagementServicesPort parameter causes container to become Unhealthy

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/nav-docker#298] opened 2018-11-06 09:19 UTC
When using 2 or more containers on one host and use them remotely we have to map the internal ports.  
I can map client port 7046 to an external port 8000, but this still doesn't work when I try to connect an RTC client to a remote container. So thanksfully you added parameter -ClientServicesPort (and -ManagementServicesPort) to New-NavContainer. 
Now, when using -ClientServicesPort 8000 and map this port with -AdditionalParameters "-p 8000:8000", I'm able to connect a remote RTC client perfecty. But for the Development environment to work, to be able to save a table and to use the debugger, I have to do the same for the -ManagementServicesPort. So when adding -ManagementServicesPort 8001 and -AdditionalParameters "-p 8001:8001", I'm perfectly able to debug and save a table. 

But here's my issue. Everythings seems to work just fine, but when adding the -ManagementServicesPort and -AdditionalParameters "-p 8001:8001" the created container goes to status = Unhealthy. 
Can you tell my if this is an issue with the -ManagementServicesPort parameter and the portmapping, because this will raise a red flag with my administrator about the container status. I've added the inspect-file, to show you the container in question. 

[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/2552368/inspect.txt)

**Comment by freddydk** [comment] 2018-12-09 10:08
Duplicate of #262

**Comment by freddydk** [comment] 2018-12-09 10:08
Generic 0.0.8.1 has been created and the latest insider builds are using this.
examples:
bcinsider.azurecr.io/bcsandbox:us-ltsc2019
and
bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019
Please try them out.
Another round of full rebuilds is scheduled to next week.

**Closed by freddydk** 2018-12-09 10:08 UTC
Labels: Will be fixed in a future version
